//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinAmp2.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPlayList
    {
        public int IdUserPlayList { get; set; }
        public int IdUser { get; set; }
        public int IdPlayList { get; set; }
    
        public virtual PlayList PlayList { get; set; }
        public virtual User User { get; set; }
    }
}
